### PR TITLE
Spike: Update Proposal Discord message styling

### PR DESCRIPTION
**Pull request by aidan-starke**
## Why

 - Move all data into the one block so as not to flood the server

## What is changing

 - Seperate `Proposal` and `Vote` fields
 - Only update `Vote` fields on vote
 - Move `ProposalStatus` to footer
 - Set colour to purple during voting, red if proposal is rejected, green otherwise

## Notes

 - During Voting
Screen Shot 2022-06-16 at 3 14 05 PM

 - After Voting
Screen Shot 2022-06-16 at 3 14 42 PM

- Long Description
Screen Shot 2022-06-16 at 3 16 53 PM

### CODE REVIEW

**Comment by ken-futureverse** [comment]
Are we losing all the details about the proposal after voting is completed?

**Comment by aidan-starke** [comment]
> Are we losing all the details about the proposal after voting is completed?

currently, can leave it in there no stress

**Comment by ken-futureverse** [comment]
yeah keep them the same please, only thing that changes are the "Status" and gutter color, green for "passed" and red for "rejected"

**Comment by aidan-starke** [comment]
sorted, dropped the votes for/against and voting buttons (votes get removed from storage once proposal moves to next stage)
Screen Shot 2022-06-16 at 4 36 10 PM

**Review by ken-futureverse — APPROVED** [review]

**Pull request merged**
